project_id = "wsuljngcdfagrkbtxltb"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.create-daily-room]
verify_jwt = false

[functions.end-call]
verify_jwt = false

[functions.calculate-family-lines]
verify_jwt = false
